-- Forward replacement only: retain all existing FMP research evidence.
-- Convert timezone-free whole seconds, subtract the explicit signed offset,
-- and add exact microseconds. SQLite's offset and fractional rounding limits
-- must not weaken the project's accepted aware-datetime contract.
DROP TRIGGER company_fmp_research_row_monotonic_capture;
CREATE TRIGGER company_fmp_research_row_monotonic_capture BEFORE INSERT ON company_fmp_research_rows
WHEN ((CAST(strftime('%s',substr(NEW.captured_at,1,19)||'Z') AS INTEGER)-(CASE WHEN substr(NEW.captured_at,-1)='Z' THEN 0 ELSE (CASE WHEN substr(NEW.captured_at,-6,1)='-' THEN -1 ELSE 1 END)*(CAST(substr(NEW.captured_at,-5,2) AS INTEGER)*3600+CAST(substr(NEW.captured_at,-2) AS INTEGER)*60) END))*1000000+(CASE WHEN substr(NEW.captured_at,20,1)='.' THEN CAST(substr(substr(NEW.captured_at,21,length(NEW.captured_at)-20-CASE WHEN substr(NEW.captured_at,-1)='Z' THEN 1 ELSE 6 END)||'000000',1,6) AS INTEGER) ELSE 0 END)) IS NULL OR EXISTS(
 SELECT 1 FROM company_fmp_research_rows
 WHERE natural_identity=NEW.natural_identity AND (
 ((CAST(strftime('%s',substr(captured_at,1,19)||'Z') AS INTEGER)-(CASE WHEN substr(captured_at,-1)='Z' THEN 0 ELSE (CASE WHEN substr(captured_at,-6,1)='-' THEN -1 ELSE 1 END)*(CAST(substr(captured_at,-5,2) AS INTEGER)*3600+CAST(substr(captured_at,-2) AS INTEGER)*60) END))*1000000+(CASE WHEN substr(captured_at,20,1)='.' THEN CAST(substr(substr(captured_at,21,length(captured_at)-20-CASE WHEN substr(captured_at,-1)='Z' THEN 1 ELSE 6 END)||'000000',1,6) AS INTEGER) ELSE 0 END)) IS NULL OR ((CAST(strftime('%s',substr(captured_at,1,19)||'Z') AS INTEGER)-(CASE WHEN substr(captured_at,-1)='Z' THEN 0 ELSE (CASE WHEN substr(captured_at,-6,1)='-' THEN -1 ELSE 1 END)*(CAST(substr(captured_at,-5,2) AS INTEGER)*3600+CAST(substr(captured_at,-2) AS INTEGER)*60) END))*1000000+(CASE WHEN substr(captured_at,20,1)='.' THEN CAST(substr(substr(captured_at,21,length(captured_at)-20-CASE WHEN substr(captured_at,-1)='Z' THEN 1 ELSE 6 END)||'000000',1,6) AS INTEGER) ELSE 0 END))>=((CAST(strftime('%s',substr(NEW.captured_at,1,19)||'Z') AS INTEGER)-(CASE WHEN substr(NEW.captured_at,-1)='Z' THEN 0 ELSE (CASE WHEN substr(NEW.captured_at,-6,1)='-' THEN -1 ELSE 1 END)*(CAST(substr(NEW.captured_at,-5,2) AS INTEGER)*3600+CAST(substr(NEW.captured_at,-2) AS INTEGER)*60) END))*1000000+(CASE WHEN substr(NEW.captured_at,20,1)='.' THEN CAST(substr(substr(NEW.captured_at,21,length(NEW.captured_at)-20-CASE WHEN substr(NEW.captured_at,-1)='Z' THEN 1 ELSE 6 END)||'000000',1,6) AS INTEGER) ELSE 0 END))))
BEGIN SELECT RAISE(ABORT,'FMP research revisions require increasing capture time'); END;
